# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  samplesweatherforecastapi:
    image: samplesweatherforecastapi
    build:
      context: .
      dockerfile: src/Samples.WeatherForecast.Api/Dockerfile
    ports:
      - 80
